apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

configurations:
- kustomizeconfig.yaml

images:
- name: controller
  newName: quay.lab.brtrm.dev/marius/oc-mirror-operator-controller
  newTag: latest
- name: dashboard
  newName: quay.lab.brtrm.dev/marius/oc-mirror-operator-dashboard
  newTag: latest
- name: manager
  newName: quay.lab.brtrm.dev/marius/oc-mirror-operator-manager
  newTag: latest
- name: oauth-proxy
  newName: quay.io/openshift/origin-oauth-proxy
  newTag: latest
- name: worker
  newName: quay.lab.brtrm.dev/marius/oc-mirror-operator-worker
  newTag: latest
