apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oc-mirror
  name: oc-mirror-oc-mirror-controller-role
rules:
- apiGroups:
  - mirror.openshift.io
  resources:
  - mirrortargets
  - imagesets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - mirror.openshift.io
  resources:
  - mirrortargets/finalizers
  - imagesets/finalizers
  verbs:
  - update
- apiGroups:
  - mirror.openshift.io
  resources:
  - mirrortargets/status
  - imagesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
