apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2026-04-17T12:46:11Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: ocp-mirror.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: A implementation of oc-mirror as k8s operator
  displayName: oc-mirror-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mirror
  - ocp
  - images
  links:
  - name: Ocp Mirror
    url: https://ocp-mirror.domain
  maintainers:
  - email: marius@brtrm.de
    name: Marius Bertram
  maturity: alpha
  provider:
    name: Marius Bertram
    url: github.com/mariusbertram/oc-mirror-operator
  version: 0.0.1
