# This rule is not used by the project ocp-mirror itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to mirror.openshift.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ocp-mirror
    app.kubernetes.io/managed-by: kustomize
  name: imageset-viewer-role
rules:
- apiGroups:
  - mirror.openshift.io
  resources:
  - imagesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mirror.openshift.io
  resources:
  - imagesets/status
  verbs:
  - get
