apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ocp-mirror.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: A implementation of oc-mirror as k8s operator
  displayName: oc-mirror-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mirror
  - ocp
  - images
  links:
  - name: Ocp Mirror
    url: https://ocp-mirror.domain
  maintainers:
  - email: marius@brtrm.de
    name: Marius Bertram
  maturity: alpha
  provider:
    name: Marius Bertram
    url: github.com/mariusbertram/oc-mirror-operator
  version: 0.0.0
